spring:
  application:
    name: pos-delivery
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: root
  cloud:
    stream:
      bindings:
        order-consumer:
          binder: rabbit
          destination: order-handler
          group: default

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
